config/routes.rb
Mapgen::Application.routes.draw do
  resources :map_renders

  resources :maps do
    resources :map_renders
  end

  root :to => "maps#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :maps
end

app/models/map.rb
class Map < ActiveRecord::Base
  PAPER_SIZES = ["a4", "a3", "a2", "a1", "a0"]
  validates_inclusion_of :paper_size, :in => PAPER_SIZES

  ORIENTATIONS = ["landscape", "portrait"]
  validates_inclusion_of :orientation, :in => ORIENTATIONS

  validates_presence_of :title, :left, :right, :top, :bottom

  validates_format_of :title, :with => /\A[\w \.,]+\z/

  has_and_belongs_to_many :categories do
    def to_s
      map(&:title).to_sentence
    end
  end

  has_many :map_renders

  # Create a new render whenever the map is changed
  after_save :generate_render

  # Return map bounds in a human readable form
  def bounds
    "#{top},#{left}:#{bottom},#{right}"
  end

  def generate_render
    map_renders.create!
  end
end

app/models/map_render.rb
class MapRender < ActiveRecord::Base
  RENDER_EXECUTABLE = "/home/otm/projects/eqnz-ocitysmap/ocitysmap2-render"
  RENDER_WORK_DIR = "/home/otm/projects"
  OUTPUT_DIR = '/home/otm/projects/eqnz/www/print/custom_maps'
  OUTPUT_URL = 'http://maps.eq.org.nz/print/custom_maps'
  STATUSES = ['pending', 'started', 'complete']
  validates_inclusion_of :status, :in => STATUSES

  belongs_to :map

  default_scope order("created_at DESC").limit(5)

  after_create :render

  def to_s
    "#{id} #{map.left} #{map.top} #{map.right} #{map.bottom} #{map.paper_size} #{map.orientation} #{map.include_index} #{map.category_ids.join(',')} #{map.title}"
  end

  def pending
    status == 'pending'
  end
  def started
    status == 'started'
  end
  def complete
    status == 'complete'
  end

  def render
    self.status = 'started'
    save!
    logger.debug render_command
    if Rails.env == 'production'
      system "cd #{RENDER_WORK_DIR} && #{render_command}"
    end
    self.status = 'complete'
    save!
  end
  # Always use delayed_job to run this
  handle_asynchronously :render

  def index_style
    return "plain" unless map.include_index?
    map.orientation == 'portrait' ? "single_page_index_bottom" : "single_page_index_side"
  end

  def filename
    map.title.gsub(' ','_') + '-' + id.to_s
  end

  def categories_as_arguments
    map.categories.map {|c| "-c #{c.id}"}.join(' ')
  end

  def render_command
    "#{RENDER_EXECUTABLE} -L en_NZ.UTF-8 -b #{map.top},#{map.left} #{map.bottom},#{map.right} --paper-format=#{map.paper_size.upcase} -t '#{map.title}' -o #{map.orientation} -l #{index_style} #{categories_as_arguments} -p #{OUTPUT_DIR}/#{filename}"
  end

  def pdf_url
    OUTPUT_URL + '/' + filename + '.pdf'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/map_renders_controller.rb
class MapRendersController < ApplicationController
  # GET /map_renders
  # GET /map_renders.xml
  def index
    @map_renders = MapRender.where(:status => 'pending')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @map_renders }
      format.txt
    end
  end

  # GET /map_renders/1.js
  def show
    @map_render = MapRender.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  # PUT /map_renders/1
  # PUT /map_renders/1.xml
  def update
    @map_render = MapRender.find(params[:id])

    respond_to do |format|
      if @map_render.update_attributes(params[:map_render])
        format.html { redirect_to(@map_render, :notice => 'Map render was successfully updated.') }
        format.xml  { head :ok }
        format.txt  { render :text => 'OK' }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @map_render.errors, :status => :unprocessable_entity }
        format.txt  { render :text => 'ERR: ' + @map_render.errors.full_messages.to_sentence }
      end
    end
  end

  def create
    @map = Map.find(params[:map_id])
    @map_render = @map.map_renders.create!
    redirect_to @map
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  # GET /maps
  # GET /maps.xml
  def index
    @maps = Map.all :order => 'title'

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @maps }
    end
  end

  # GET /maps/1
  # GET /maps/1.xml
  def show
    @map = Map.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.xml
  def new
    @map = Map.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/1/edit
  def edit
    @map = Map.find(params[:id])
  end

  # POST /maps
  # POST /maps.xml
  def create
    @map = Map.new(params[:map])

    respond_to do |format|
      if @map.save
        format.html { redirect_to(@map, :notice => 'Map was successfully created.') }
        format.xml  { render :xml => @map, :status => :created, :location => @map }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.xml
  def update
    @map = Map.find(params[:id])

    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to(@map, :notice => 'Map was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.xml
  def destroy
    @map = Map.find(params[:id])
    @map.destroy

    respond_to do |format|
      format.html { redirect_to(maps_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_renders_helper.rb
module MapRendersHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Christchurch Recovery Map</title> 
  <meta name="description" content="Community information for the Christchurch Earthquake of 22 Feb 2011"> 
  <meta name="author" content="CrisisCampNZ"> 

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" type="text/css" href="http://eq.org.nz/themes/ccnz/css/style.css" /> 
  <link rel="stylesheet" type="text/css" href="http://eq.org.nz/media/css/jquery-ui-themeroller.css" /> 
  <!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="http://eq.org.nz/media/css/iehacks.css" />
  <![endif]--><!--[if IE 7]><link rel="stylesheet" type="text/css" href="http://eq.org.nz/media/css/ie7hacks.css" />
  <![endif]--><!--[if IE 6]><link rel="stylesheet" type="text/css" href="http://eq.org.nz/media/css/ie6hacks.css" />
  <![endif]-->
  <link rel="stylesheet" type="text/css" href="http://eq.org.nz/media/css/openlayers.css" /> 
  <link rel="stylesheet" type="text/css" href="http://eq.org.nz/plugins/fullscreenmap/views/css/fullscreenmap.css" />
  <link rel="stylesheet" type="text/css" href="http://eq.org.nz/plugins/fullscreenmap/views/css/colorbox.css" />
  <link rel="alternate" type="application/rss+xml" href="http://eq.org.nz/feed/" title="RSS2" />
  <link rel="shortcut icon" href="http://eq.org.nz/favicon.ico">
  <link rel="apple-touch-icon" href="http://eq.org.nz/apple-touch-icon.png">
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
  <script src="http://www.openlayers.org/api/OpenLayers.js"></script>
  <%= csrf_meta_tag %>
</head>
<body id="page"><div id="cboxOverlay" style="display: none; "></div><div id="colorbox" class="" style="padding-bottom: 42px; padding-right: 42px; display: none; "><div id="cboxWrapper"><div><div id="cboxTopLeft" style="float: left; "></div><div id="cboxTopCenter" style="float: left; "></div><div id="cboxTopRight" style="float: left; "></div></div><div style="clear:left"><div id="cboxMiddleLeft" style="float: left; "></div><div id="cboxContent" style="float: left; "><div id="cboxLoadedContent" style="width: 0px; height: 0px; overflow-x: hidden; overflow-y: hidden; " class=""></div><div id="cboxLoadingOverlay" class=""></div><div id="cboxLoadingGraphic" class=""></div><div id="cboxTitle" class=""></div><div id="cboxCurrent" class=""></div><div id="cboxNext" class=""></div><div id="cboxPrevious" class=""></div><div id="cboxSlideshow" class=""></div><div id="cboxClose" class=""></div></div><div id="cboxMiddleRight" style="float: left; "></div></div><div style="clear:left"><div id="cboxBottomLeft" style="float: left; "></div><div id="cboxBottomCenter" style="float: left; "></div><div id="cboxBottomRight" style="float: left; "></div></div></div><div style="position:absolute; width:9999px; visibility:hidden; display:none"></div></div>
	<!-- wrapper -->
	<div class="rapidxwpr floatholder">

		<!-- header -->
		<div id="header">

			<!-- searchbox -->
			<div id="searchbox">
					<ul class="useful_links">
						<li><a class="skip-link" href="http://eq.org.nz/#main" title="Skip to content" accesskey="[">Skip to content</a></li>						
						<li>Useful Links:</li>
						<li><a href="http://eq.org.nz/page/index/2">Google Person Finder</a></li><li><a href="http://eq.org.nz/page/index/3">Accommodation</a></li><li><a href="http://eq.org.nz/page/index/4">Student Volunteer Army</a></li><li><a href="http://eq.org.nz/page/index/5">Business</a></li>					</ul>

				<!-- searchform -->
				<div class="search-form"><form method="get" id="search" action="http://eq.org.nz/search/"><ul><li><input type="text" name="k" value="" class="text"></li><li><input type="submit" name="b" class="searchbtn" value="search"></li></ul></form></div>				<!-- / searchform -->

			</div>
			<!-- / searchbox -->
			
			<!-- logo -->
			<div id="logo">
				<h1><a href="http://eq.org.nz/">Christchurch Recovery Map</a></h1>
				<span>Community information for the Christchurch Earthquake of 22 Feb 2011.</span>
			</div>
			<!-- / logo -->
			
			<!-- submit incident -->
			<div class="submit-incident clearingfix"><a href="http://eq.org.nz/reports/submit">Submit a Report</a></div>			<!-- / submit incident -->
			
		</div>
		<!-- / header -->

		<!-- main body -->
		<div id="middle">
			<div class="background layoutleft">

				<!-- mainmenu -->
				<div id="mainmenu" class="clearingfix">
					<ul>
            <li><a style="background: #c7201a;" href="http://eq.org.nz/main">Main Home</a></li><li><a href="http://maps.eq.org.nz/">Maps</a></li><li><a href="http://maps.eq.org.nz/print">Printable Maps</a></li><li><%= link_to 'Custom maps', root_url, :class => 'active' %></li><li><a href="http://maps.eq.org.nz/kml">KML Exports</a></li></ul>

				</div>
				<!-- / mainmenu -->

        <!-- main body -->
        <div id="main" class="clearingfix">
            <div id="mainmiddle" class="floatbox withright">

                <!-- content column -->
                <div id="content" class="clearingfix">
                    <div class="floatbox">
                      <%= yield %>
                    </div>
                    <!-- / floatbox -->
                </div>
                <!-- / content column -->

            </div>
        </div>
        <!-- / main body -->

			</div>
		</div>
		<!-- / main body -->

	</div>
	<!-- / wrapper -->
	
	<!-- footer -->
	<div id="footer" class="clearingfix">
 
		<div id="underfooter"></div>
				
		<!-- footer content -->
		<div class="rapidxwpr floatholder">
 
			<!-- footer credits -->
			<div class="footer-credits">
				Powered by the &nbsp;<a href="http://www.ushahidi.com/"><img src="http://eq.org.nz//media/img/footer-logo.png" alt="Ushahidi" style="vertical-align:middle"></a>&nbsp; Platform
			</div>
			<!-- / footer credits -->
		
			<!-- footer menu --> 
			<div class="footermenu"> 
				<ul class="clearingfix"> 
					<li><a class="item1" href="http://eq.org.nz/">Home</a></li> 
					<li><a href="http://eq.org.nz/reports/submit">Submit a Report</a></li> 
					<li><a href="http://eq.org.nz/alerts">Get Alerts</a></li> 
					<li><a href="http://eq.org.nz/contact">Contact Us</a></li> 
									</ul> 
				      		<p>The content of this site is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/nz/">Creative Commons Attribution 3.0 New Zealand License</a>. To satisfy attribution requirements, include "Source: http://eq.org.nz"
in your derived content.
 
This website is provided as is, and your use of it is <strong>exclusively at your own risk</strong>. You are solely responsible for any liability, loss, injury or risk which is incurred as a direct or indirect result of the use of any of the content or information on this website and/or any website linked to from this website.</p> 
      				</div> 
			<!-- / footer menu --> 

      
			<h2 class="feedback_title" style="clear:both">
				<a href="http://feedback.ushahidi.com/fillsurvey.php?sid=2">Provide Feedback</a>
			</h2>

 
		</div>
		<!-- / footer content -->
 
	</div>
	<!-- / footer -->
	
	  <!--[if lt IE 7 ]>
	    <script src="js/libs/dd_belatedpng.js"></script>
	    <script> DD_belatedPNG.fix('img, .png_bg'); </script>
	  <![endif]-->

		<!-- Piwik --><script type="text/javascript">$(document).ready(function(){$('#piwik').load('http://tracker.ushahidi.com/piwik/piwik.php?idsite=13005&rec=1');});</script><div id="piwik"></div><!-- End Piwik Tag -->		
		<!-- Task Scheduler -->
		<!--<img src="http://eq.org.nz/media/img/spacer.gif" alt="" height="1" width="1" border="0" onload="runScheduler(this)" />-->
</body>
</html>

app/views/map_renders/_form.html.erb
<%= form_for(@map_render) do |f| %>
  <% if @map_render.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map_render.errors.count, "error") %> prohibited this map_render from being saved:</h2>

      <ul>
      <% @map_render.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :map %><br />
    <%= f.text_field :map %>
  </div>
  <div class="field">
    <%= f.label :complete %><br />
    <%= f.check_box :complete %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/map_renders/_map_render.html.erb
<% div_for map_render do %>
  <% if map_render.complete %>
    <%= image_tag 'map.png' %> <%= link_to 'Download PDF', map_render.pdf_url %> <em class="hovershow"><%= map_render.created_at %></em>
  <% elsif map_render.started %>
    <%= image_tag 'ajax-loader.gif' %> <%= map_render.created_at %> - Render in progress ...
  <% else %>
    <%= image_tag 'ajax-loader.gif' %> <%= map_render.created_at %> - Awaiting render ...
  <% end %>
  <% unless map_render.complete %>
    <script type="text/javascript">
      setTimeout(function() {
        $.getScript('<%= map_render_path(map_render, :format => 'js') %>');
      }, 5000);
    </script>
  <% end %>
<% end %>

app/views/map_renders/edit.html.erb
<h1>Editing map_render</h1>

<%= render 'form' %>

<%= link_to 'Show', @map_render %> |
<%= link_to 'Back', map_renders_path %>

app/views/map_renders/index.html.erb
<h1>Listing map_renders</h1>

<table>
  <tr>
    <th>Map</th>
    <th>Complete</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @map_renders.each do |map_render| %>
  <tr>
    <td><%= map_render.map %></td>
    <td><%= map_render.complete %></td>
    <td><%= map_render.url %></td>
    <td><%= link_to 'Show', map_render %></td>
    <td><%= link_to 'Edit', edit_map_render_path(map_render) %></td>
    <td><%= link_to 'Destroy', map_render, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Map render', new_map_render_path %>

app/views/map_renders/index.txt.erb
<% @map_renders.each do |map_render| -%>
<%= map_render.to_s %>
<% end -%>

app/views/map_renders/new.html.erb
<h1>New map_render</h1>

<%= render 'form' %>

<%= link_to 'Back', map_renders_path %>

app/views/map_renders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Map:</b>
  <%= @map_render.map %>
</p>

<p>
  <b>Complete:</b>
  <%= @map_render.complete %>
</p>

<p>
  <b>Url:</b>
  <%= @map_render.url %>
</p>


<%= link_to 'Edit', edit_map_render_path(@map_render) %> |
<%= link_to 'Back', map_renders_path %>

app/views/map_renders/show.js.erb
$('#map_render_<%= @map_render.id %>').replaceWith(
  '<%= escape_javascript(render(@map_render, :format => 'html')) %>'
);

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :paper_size %><br />
    <%= f.select :paper_size, Map::PAPER_SIZES %>
  </div>
  <div class="field">
    <%= f.label :orientation %><br />
    <%= f.select :orientation, Map::ORIENTATIONS %>
  </div>
  <div class="field">
    <%= f.label :include_index %><br />
    <%= f.check_box :include_index %>
  </div>
  <%= render :partial => 'map', :object => @map, :locals => {:editable => true} %>
  <script type="text/javascript">
    function updateBoundsForm() {
      bounds = map.getExtent().transform(map.getProjectionObject(), new OpenLayers.Projection("EPSG:4326"));
      document.getElementById('map_left').value = bounds.left;
      document.getElementById('map_top').value = bounds.top;
      document.getElementById('map_right').value = bounds.right;
      document.getElementById('map_bottom').value = bounds.bottom;
    }
    map.events.register('zoomend', map, updateBoundsForm); 
    map.events.register('moveend', map, updateBoundsForm); 
  </script>
  <div class="field">
    <%= f.label :left %>
    <%= f.text_field :left, :size => 12 %>
    <%= f.label :top %>
    <%= f.text_field :top, :size => 12 %>
    <%= f.label :right %>
    <%= f.text_field :right, :size => 12 %>
    <%= f.label :bottom %>
    <%= f.text_field :bottom, :size => 12 %>
  </div>
  <div class="field">
    <%= f.label :category_ids %><br />
    <%= f.collection_select :category_ids, Category.all.sort_by(&:title),
                            :id, :title, {}, :multiple => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/_map.html.erb
<div id="map" style="width:600px;height:600px;"></div>
<script type="text/javascript">
  <% if defined?(editable) && editable %>
  var map = new OpenLayers.Map('map');
  <% else %>
  var map = new OpenLayers.Map('map', {controls:[]});
  <% end %>
  map.addLayer(new OpenLayers.Layer.OSM());
  bounds = new OpenLayers.Bounds();
  bounds.extend(new OpenLayers.LonLat(<%= map.left %>, <%= map.top %>)
      .transform(new OpenLayers.Projection("EPSG:4326"), map.getProjectionObject()));
  bounds.extend(new OpenLayers.LonLat(<%= map.right %>, <%= map.bottom %>)
      .transform(new OpenLayers.Projection("EPSG:4326"), map.getProjectionObject()));
  map.zoomToExtent(bounds);
</script>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<h1>Listing maps</h1>

<div class="buttonlink">
  <%= link_to 'New Map', new_map_path %>
</div>

<% @maps.each do |map| %>
  <div id="map_<%= map.id %>" class="mapdetails">
    <h3><%= link_to map.title, map %></h3>
    <div class="details">
      <span>
        <%= render map.map_renders.first if map.map_renders.first %>
      </span>
      <span class="hovershow">
        Paper: <%= map.paper_size %>, Orientation: <%= map.orientation %>,
        <%= pluralize map.categories.count, 'report category' %>
        <%= link_to 'Show', map %> |
        <%= link_to 'Edit', edit_map_path(map) %> |
        <%= link_to 'Delete', map, :confirm => 'Are you sure?', :method => :delete %>
      </span>
    </div>
  </div>
<% end %>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @map.title %></h1>

<%= button_to('Regenerate this map', map_map_renders_path(@map, :method => :post)) %>
<hr>
<h2>Downloads</h2>
<ul>
<% @map.map_renders.each do |map_render| %>
  <li>
  <%= render map_render %>
  </li>
<% end %>
</ul>
<hr>

<%= render :partial => 'map', :object => @map %>

<p>
  <b>Paper size:</b>
  <%= @map.paper_size %>
  <b>Orientation:</b>
  <%= @map.orientation %>
  <b>Include index:</b>
  <%= @map.include_index %>
</p>

<p>
  <b>Geographic area:</b>
  <%= @map.bounds %>
</p>

<p>
  <b>Categories:</b>
  <%= @map.categories.map(&:title).to_sentence %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>